pipeline {
    agent any

    tools { 
        maven 'maven-3.8.6'
        jdk 'jdk17'
    }

    stages {
        stage('Clean') {
            steps {
                dir("ContinuousIntegration/maven-hello-word") {
                    sh 'mvn clean'
                }
            }
        }
        stage('Compile') {
            steps {
                dir("ContinuousIntegration/maven-hello-word") {
                    sh 'mvn compile'
                }
            }
        }
        stage('Clean Build') {
            steps {
                dir("ContinuousIntegration/maven-hello-word") {
                    sh 'mvn build'
                }
            }
        }
        stage('Test') {
            steps {
                dir("ContinuousIntegration/maven-hello-word") {
                    sh 'mvn test'
                }
            }
        }
        stage('Package') {
            steps {
                dir("ContinuousIntegration/maven-hello-word") {
                    sh 'mvn package'
                }
            }
        }
    }
}