pipeline {
    agent any
    tools { 
        maven 'maven-3.8.7'
        jdk 'jdk17'
    }

    stages {
        stage('Clean') {
            steps {
                dir("ContinuousIntegration/maven-hello-world") {
                    sh 'mvn clean'
                }
            }
        }
        stage('Compile') {
            steps {
                dir("ContinuousIntegration/maven-hello-world") {
                    sh 'mvn compile'
                }
            }
        }
        stage('Test') {
            steps {
                dir("ContinuousIntegration/maven-hello-world") {
                    sh 'mvn test'
                }
            }
        }
        stage('Package') {
            steps {
                dir("ContinuousIntegration/maven-hello-world") {
                    sh 'mvn package'
                }
            }
        }
    }
    
    post {
        always {
            archiveArtifacts artifacts: 'ContinuousIntegration/maven-hello-world/target/diambar-1.0-SNAPSHOT.jar', onlyIfSuccessful: true
        }
    }
}