apiVersion: v1
kind: Service
metadata:
  labels:
    name: pma-svc
  name: pmaservice
  namespace: devops-k8s-example
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: pma