pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                dir("Containers/simple-flask-app") {
                    sh 'docker build -t simple-flask-app:latest .'
                }
            }
        }
        stage('Tag image') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Run Docker Container') {
            steps {
                echo 'Deploying....'
            }
        }
        stage('Test Docker Conntainer') {
            steps {
                echo 'Deploying....'
            }
        }

        stage('Clean Environment') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}