pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                dir("Containers/simple-flask-app") {
                    sh 'docker build -t simple-flask-app:latest .'
                }
            }
        }
        stage('Run Docker Container') {
            steps {
                sh 'docker run -d -p 8090:8080 --name test-container simple-flask-app:latest'
            }
        }
        stage('Test Docker Conntainer') {
            steps {
               sh 'curl http://localhost:8090'
            }
        }

        stage('Clean Environment') {
            steps {
                sh 'docker stop test-container'
                sh 'docker rm test-container'
            }
        }
    }
}