pipeline{
    agent any

    stages
    {
        stage('Build Image'){
            steps{
                dir("Containers/simple-php-app") {
                    sh "docker build -t php-app:1.0.0 ."
                }
            }
        }
        stage('Run container'){
            steps{
                sh "docker run -d -p 8008:80 --name container-test php-app:1.0.0"
            }
        }
    }
}