pipeline{
    agent any

    stages
    {
        stage('Build Image'){
            steps{
                dir("Containers/simple-php-app") {
                    sh "docker build -t php-app:1.0.0 ."
                }
            }
        }
    }
}