apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-volume
spec:
  containers:
  - name: container-with-limit
    image: nginx
    resources:
      limits:
        cpu: 2
      requests:
        cpu: 1
    volumeMounts:
      # name must match the volume name below
      - name: atos-secret
        mountPath: /etc/atos/gmail_account
        readOnly: true
  volumes:
    - name: atos-secret
      secret:
        secretName: mysecret 