apiVersion: v1
kind: Pod
metadata:
  name: pod-resources-cpu
spec:
  containers:
  - name: pod-resources-cpu-ctr
    image: nginx
    resources:
      limits:
        cpu: 0.5
      requests:
        cpu: 0.25

#kubectl delete -f pod/pod-resources-cpu.yaml
#kubectl get pod pod-resources-cpu -o yaml
#kubectl create -f pod/pod-resources-cpu.yaml