apiVersion: v1
kind: Pod
metadata:
  name: pod-resources-cpu
  #namespace: cpu-request-limit-namespace
  namespace: quota-example
spec:
  containers:
  - name: container-with-limit
    image: nginx
    resources:
      limits:
        cpu: 2
      requests:
        cpu: 1

#kubectl delete -f pod/pod-resources-cpu.yaml
#kubectl get pod pod-resources-cpu -o yaml
#kubectl create -f pod/pod-resources-cpu.yaml