apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-env
spec:
  containers:
  - name: container-with-limit
    image: nginx
    resources:
      limits:
        cpu: 2
      requests:
        cpu: 1
    env:
    - name: QUESTION
      value: ANSWER
    - name: GMAIL_USERNAME
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: username
    - name: GMAIL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
    - name: GMAIL_SMTP
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: url
   