apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx-svc
  name: nginx-svc
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30007
  selector:
    app: nginx