apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx-svc-nodeport
  name: nginx-svc-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx

#kubectl create -f service/service-nodeport.yml
#minikube service nginx-svc-nodeport --url