#Request: Ce que demande un pod / Limit: Ce qu'il ne peut pas dépasser
apiVersion: v1
kind: Namespace
metadata:
  name: cpu-request-limit-namespace

---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: cpu-request-limit-namespace
spec:
  limits:
  - default:
      cpu: 1
    defaultRequest:
      cpu: 0.5
    type: Container

---
apiVersion: v1
kind: Pod
metadata:
  name: default-cpu-po
  namespace: cpu-request-limit-namespace
spec:
  containers:
  - name: default-cpu-demo-ctr
    image: nginx



#https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-cpu
#https://kubernetes.io/docs/concepts/policy/limit-range/
#kubectl get limitrange -n cpu-request-limit-namespace -o yaml
#kubectl get pod default-cpu-po -n memory-request-limit-namespace -o yaml