apiVersion: v1
kind: Namespace
metadata:
  labels:
    env: prod
  name: production

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    env: dev
  name: development

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    env: test
  name: testing